export const Types = {
  GET_DIRECT_REPORTS: 'GET_DIRECT_REPORTS',
  GET_DIRECT_REPORT: 'GET_DIRECT_REPORT',
  ADD_DIRECT_REPORT: 'ADD_DIRECT_REPORT',
  REMOVE_DIRECT_REPORT: 'REMOVE_DIRECT_REPORT',
  UPDATE_DIRECT_REPORT: 'UPDATE_DIRECT_REPORT',
}
