export const Types = {
  GET_ALL_TOKENS: 'GET_ALL_TOKENS',
  NEW_TOKEN: 'NEW_TOKEN',
  SET_TOKEN_DATA: 'SET_TOKEN_DATA',
  GET_TOKEN_DETAIL: 'GET_TOKEN_DETAIL',
  DELETE_TOKEN: 'DELETE_TOKEN',
  RESTORE_TOKEN: 'RESTORE_TOKEN',
}
