export const Types = {
    GET_EMPLOYEES: 'GET_EMPLOYEES',
    GET_EMPLOYEE: 'GET_EMPLOYEE',
    ADD_EMPLOYEE: 'ADD_EMPLOYEE',
    REMOVE_EMPLOYEE: 'REMOVE_EMPLOYEE',
    UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
    ADD_EMPLOYEE_FILTER: 'ADD_EMPLOYEE_FILTER',
    APPLY_SEARCH_RESULTS: 'APPLY_SEARCH_RESULTS',
}
