export const Types = {
  GET_CONTACT_DETAILS: 'GET_CONTACT_DETAILS',
  GET_CONTACT_DETAIL: 'GET_CONTACT_DETAIL',
  ADD_CONTACT_DETAIL: 'ADD_CONTACT_DETAIL',
  REMOVE_CONTACT_DETAIL: 'REMOVE_CONTACT_DETAIL',
  UPDATE_CONTACT_DETAIL: 'UPDATE_CONTACT_DETAIL',
}
