export const Types = {
    GET_INFORMATION_REQUESTS: 'GET_INFORMATION_REQUESTS',
    GET_INFORMATION_REQUEST: 'GET_INFORMATION_REQUEST',
    UPDATE_INFORMATION_REQUEST: 'UPDATE_INFORMATION_REQUEST',
    ADD_INFORMATION_REQUEST_FILTER: 'ADD_INFORMATION_REQUEST_FILTER',
    GET_FILTER_PARAMS: 'GET_FILTER_PARAMS',
}
