export const Types = {
  GET_PREVIOUS_POSITIONS: 'GET_PREVIOUS_POSITIONS',
  GET_PREVIOUS_POSITION: 'GET_PREVIOUS_POSITION',
  ADD_PREVIOUS_POSITION: 'ADD_PREVIOUS_POSITION',
  REMOVE_PREVIOUS_POSITION: 'REMOVE_PREVIOUS_POSITION',
  UPDATE_PREVIOUS_POSITION: 'UPDATE_PREVIOUS_POSITION',
}
