export const Types = {
  GET_PREVIOUS_RANKS: 'GET_PREVIOUS_RANKS',
  GET_PREVIOUS_RANK: 'GET_PREVIOUS_RANK',
  ADD_PREVIOUS_RANK: 'ADD_PREVIOUS_RANK',
  REMOVE_PREVIOUS_RANK: 'REMOVE_PREVIOUS_RANK',
  UPDATE_PREVIOUS_RANK: 'UPDATE_PREVIOUS_RANK',
}
