export const Types = {
  GET_ALL_NOMINEES: 'GET_ALL_NOMINEES',
  NEW_NOMINEE: 'NEW_NOMINEE',
  SET_NOMINEE_DATA: 'SET_NOMINEE_DATA',
  GET_NOMINEE_DETAIL: 'GET_NOMINEE_DETAIL',
  DELETE_NOMINEE: 'DELETE_NOMINEE',
  MAKE_CANDIDATE: 'MAKE_CANDIDATE',
}
