export const Types = {
  GET_DEPENDANTS: 'GET_DEPENDANTS',
  GET_DEPENDANT: 'GET_DEPENDANT',
  ADD_DEPENDANT: 'ADD_DEPENDANT',
  REMOVE_DEPENDANT: 'REMOVE_DEPENDANT',
  UPDATE_DEPENDANT: 'UPDATE_DEPENDANT',
}
