export const Types = {
  GET_JOB_DETAILS: 'GET_JOB_DETAILS',
  GET_JOB_DETAIL: 'GET_JOB_DETAIL',
  ADD_JOB_DETAIL: 'ADD_JOB_DETAIL',
  REMOVE_JOB_DETAIL: 'REMOVE_JOB_DETAIL',
  UPDATE_JOB_DETAIL: 'UPDATE_JOB_DETAIL',
}
