export const Types = {
  REQUEST_TIME_OFF: 'REQUEST_TIME_OFF',
  GET_LEAVE_TYPES: 'GET_LEAVE_TYPES',
  GET_TIME_OFF_REQUESTS: 'GET_TIME_OFF_REQUESTS',
  GET_TIME_OFF: 'GET_TIME_OFF',
  CHANGE_LEAVE_STATUS: 'CHANGE_LEAVE_STATUS',
  GET_HOLIDAYS: 'GET_HOLIDAYS',
  ADD_TIME_OFF_FILTER: 'ADD_TIME_OFF_FILTER',
}
