export const Types = {
  GET_QUALIFICATIONS: 'GET_QUALIFICATIONS',
  GET_QUALIFICATION: 'GET_QUALIFICATION',
  ADD_QUALIFICATION: 'ADD_QUALIFICATION',
  REMOVE_QUALIFICATION: 'REMOVE_QUALIFICATION',
  UPDATE_QUALIFICATION: 'UPDATE_QUALIFICATION',
}
