export const Types = {
    GET_ALL_CANDIDATES: 'GET_ALL_CANDIDATES',
    GET_ELECTION_CANDIDATES: 'GET_ELECTION_CANDIDATES',
    NEW_CANDIDATE: 'NEW_CANDIDATE',
    SET_CANDIDATE_DATA: 'SET_CANDIDATE_DATA',
    GET_CANDIDATE_DETAIL: 'GET_CANDIDATE_DETAIL',
    GET_CANDIDATE_TOKEN: 'GET_CANDIDATE_TOKEN',
    DELETE_CANDIDATE: 'DELETE_CANDIDATE',
}
