export const Types = {
    GET_LEAVE_REQUESTS: 'GET_LEAVE_REQUESTS',
    GET_FILTER_PARAMS: 'GET_FILTER_PARAMS',
    APPROVE_LEAVE_REQUEST: 'GET_LEAVE_REQUESTS',
    ADD_LEAVE_REQUEST_FILTER: 'ADD_LEAVE_REQUEST_FILTER'
}
