export const Types = {
  GET_COMMUNITY_SERVICES: 'GET_COMMUNITY_SERVICES',
  GET_COMMUNITY_SERVICE: 'GET_COMMUNITY_SERVICE',
  ADD_COMMUNITY_SERVICE: 'ADD_COMMUNITY_SERVICE',
  REMOVE_COMMUNITY_SERVICE: 'REMOVE_COMMUNITY_SERVICE',
  UPDATE_COMMUNITY_SERVICE: 'UPDATE_COMMUNITY_SERVICE',
}
