export const Types = {
  GET_ALL_GROUPS: 'GET_ALL_GROUPS',
  NEW_GROUP: 'NEW_GROUP',
  SET_GROUP_DATA: 'SET_GROUP_DATA',
  GET_GROUP_DETAIL: 'GET_GROUP_DETAIL',
  GET_ELECTIONS: 'GET_ELECTIONS',
  DELETE_GROUP: 'DELETE_GROUP'
}
